### ISSUE TITLE
What are you doing with Ceramic?

### ISSUE THREAD

**Issue by jeremyfa** [ceramic-engine/ceramic-engine.github.io#2]
Now that we are starting a new year, I'd like to showcase what people have been doing with Ceramic.

In order to do so, I intend to write a new blog article on Ceramic website.

Please share in replies to this issue what you have been doing with Ceramic. Even unfinished work. Feel free to provide screenshots and links if you have any!

**Comment by goldenPiGames** [comment]
I've been doing this. I think it's pretty cool: https://goldenpigames.itch.io/rhythm-magus
https://youtu.be/x4Dun-fjnj4
there are screenshots on the game page

**Comment by l0go** [comment]
@fire-h0und and I have been working on a tool for creating keyboard layouts. There is an existing tool called keyboard-layout-editor which was adequate for its time, but has lacked any updates. Our goal is to replace that tool while also giving it a much needed design refresh. It is a modular editor inspired by ``vim`` while still being simple to pick up.

Ceramic has some really nice infrastructure for creating custom shapes via the ``ceramic.Shape`` class. Using this functionality, we (aka fire-h0und) were able to create all the different shaped keys in a very efficient manner. Our previous plan would have involved complex shaders. We created a PR for Ceramic that adds our rounded rectangle shape. During that process I learned a lot about idiomatic Ceramic and have been refactoring our codebase to match this.

For UI we are using NotBilly's HaxeUI backend. During the refactoring I contained a ``ceramic.Visual`` into a HaxeUI component. It has greatly simplified the code. Once/if rounded rectangles get merged, NotBilly is going to look into adding them to the backend. Once we get to that point we will be able to make everything look even prettier! If anyone has a name suggestion, please send them our way!

GitHub: https://github.com/theKeyboardEditor/theKeyboardEditor
![Screen Shot 2024-01-29 at 1 43 09 PM](https://github.com/ceramic-engine/ceramic-engine.github.io/assets/24994565/694ec139-ac70-4134-ac0a-e64cec08c9f5)

![Screen Shot 2024-01-29 at 1 44 04 PM](https://github.com/ceramic-engine/ceramic-engine.github.io/assets/24994565/290d9b9e-de49-46f6-8677-ed9c9fa5e399)

![Screen Shot 2024-01-29 at 1 41 31 PM](https://github.com/ceramic-engine/ceramic-engine.github.io/assets/24994565/1cd7059f-e9fd-4323-b272-244bcf2ced3f)

**Comment by gaboose** [comment]
We are making a small game using Ceramic, LDtk and the Generic RPG Pack from [Estúdio Vaca Roxa](https://bakudas.itch.io/generic-rpg-pack). It's still a work in progress and doesn't have a name yet, but you play as a wizard. Looking forward to trying out the filter and shader features from Ceramic when I get closer to the polish stage.

![screenshot](https://github.com/ceramic-engine/ceramic-engine.github.io/assets/1573047/711c2033-1182-4c59-a01b-e93eb64e8bdc)

**Comment by jeremyfa** [comment]
The article is now out: https://ceramic-engine.com/blog/ceramic-2024/
